"""Chapter 3 finite group scaffolding.

These signatures are intentionally exercise-shaped: fill in the bodies by translating the
Chapter 3 group and subgroup definitions into finite brute-force checks.
"""

from __future__ import annotations

from collections.abc import Callable, Hashable, Iterable
from dataclasses import dataclass
from typing import Self

type BinaryOperation[ElementT] = Callable[[ElementT, ElementT], ElementT]
type CayleyTable[ElementT] = dict[tuple[ElementT, ElementT], ElementT]


@dataclass(frozen=True)
class FiniteGroupCandidate[ElementT: Hashable]:
    """A finite set with a proposed binary operation."""

    elements: frozenset[ElementT]
    operation: BinaryOperation[ElementT]

    @classmethod
    def from_elements(
        cls,
        elements: Iterable[ElementT],
        operation: BinaryOperation[ElementT],
    ) -> Self:
        """Build a candidate from any iterable of hashable elements."""
        element_set = frozenset(elements)
        if not element_set:
            msg = "a group candidate must have at least one element"
            raise ValueError(msg)
        return cls(element_set, operation)

    def combine(self, left: ElementT, right: ElementT) -> ElementT:
        """Apply the candidate operation."""
        return self.operation(left, right)


def zmod_elements(n: int) -> frozenset[int]:
    """Return the elements of Z_n as canonical representatives ``0`` through ``n - 1``."""
    if n <= 0:
        msg = "n must be positive"
        raise ValueError(msg)
    return frozenset(range(n))


def addition_mod(n: int) -> BinaryOperation[int]:
    """Return addition modulo ``n``."""
    if n <= 0:
        msg = "n must be positive"
        raise ValueError(msg)

    def add(left: int, right: int) -> int:
        return (left + right) % n

    return add


def multiplication_mod(n: int) -> BinaryOperation[int]:
    """Return multiplication modulo ``n``."""
    if n <= 0:
        msg = "n must be positive"
        raise ValueError(msg)

    def multiply(left: int, right: int) -> int:
        return (left * right) % n

    return multiply


def cayley_table[ElementT: Hashable](
    candidate: FiniteGroupCandidate[ElementT],
) -> CayleyTable[ElementT]:
    """Return the full operation table keyed by ordered element pairs."""
    raise NotImplementedError("exercise: compute every product a*b")


def is_closed[ElementT: Hashable](candidate: FiniteGroupCandidate[ElementT]) -> bool:
    """Check whether every product of two candidate elements is still in the set."""
    raise NotImplementedError("exercise: check closure over all ordered pairs")


def identity[ElementT: Hashable](
    candidate: FiniteGroupCandidate[ElementT],
) -> ElementT | None:
    """Return the two-sided identity element, or ``None`` if no identity exists."""
    raise NotImplementedError("exercise: find e with e*a == a == a*e for every a")


def inverse_of[ElementT: Hashable](
    candidate: FiniteGroupCandidate[ElementT],
    element: ElementT,
    identity_element: ElementT | None = None,
) -> ElementT | None:
    """Return a two-sided inverse for ``element``, or ``None`` if none exists."""
    raise NotImplementedError("exercise: find b with a*b == e == b*a")


def is_associative[ElementT: Hashable](candidate: FiniteGroupCandidate[ElementT]) -> bool:
    """Check associativity over all triples of elements."""
    raise NotImplementedError("exercise: check (a*b)*c == a*(b*c)")


def is_group[ElementT: Hashable](candidate: FiniteGroupCandidate[ElementT]) -> bool:
    """Check the Chapter 3 group axioms for a finite candidate."""
    raise NotImplementedError("exercise: combine closure, identity, inverses, associativity")


def is_abelian[ElementT: Hashable](candidate: FiniteGroupCandidate[ElementT]) -> bool:
    """Check whether every pair of elements commutes."""
    raise NotImplementedError("exercise: check a*b == b*a")


def is_subgroup[ElementT: Hashable](
    group: FiniteGroupCandidate[ElementT],
    subset: Iterable[ElementT],
) -> bool:
    """Check the Chapter 3 subgroup test for a proposed subset."""
    raise NotImplementedError("exercise: use the nonempty gh^{-1} subgroup test")


def generated_subgroup[ElementT: Hashable](
    group: FiniteGroupCandidate[ElementT],
    generators: Iterable[ElementT],
) -> frozenset[ElementT]:
    """Return the subgroup generated by repeatedly multiplying the given generators."""
    raise NotImplementedError("exercise: close generators under products and inverses")


def all_subgroups[ElementT: Hashable](
    group: FiniteGroupCandidate[ElementT],
) -> frozenset[frozenset[ElementT]]:
    """Enumerate all subgroups of a small finite group."""
    raise NotImplementedError("exercise: enumerate candidate subsets and apply is_subgroup")
